version: '3.8'

services:
  mysql:
    image: mysql:8.0.39
    container_name: mysql
    environment:
      MYSQL_DATABASE: full_stack
      MYSQL_ROOT_PASSWORD: Password1776+
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  studentsystem:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studentsystem
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/full_stack?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Password1776+
    depends_on:
      - mysql

volumes:
  mysql_data:
